/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a virtualkeyboard -c VirtualKeyboard ../interface/com.deepin.VirtualKeyboard.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "virtualkeyboard.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class VirtualKeyboard
 */

VirtualKeyboard::VirtualKeyboard(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

VirtualKeyboard::~VirtualKeyboard()
{
    // destructor
}

void VirtualKeyboard::HideKeyboard()
{
    // handle method call com.deepin.VirtualKeyboard.HideKeyboard
    QMetaObject::invokeMethod(parent(), "HideKeyboard");
}

void VirtualKeyboard::ShowKeyboard()
{
    // handle method call com.deepin.VirtualKeyboard.ShowKeyboard
    QMetaObject::invokeMethod(parent(), "ShowKeyboard");
}

